# Assignment-5: Naive Bayes Classifier (CSV dfset)

**Objective:** Implement Naive Bayes classifier using a dfset stored in CSV format and compute accuracy.

---

## Q1: Import Required Libraries

In [7]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import seaborn as sns
print('Libraries imported')

Libraries imported


## Q2: Load dfset from CSV

In [9]:
df =sns.load_dataset('iris')
df.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


## Q3: Explore dfset

In [10]:
print('Shape:', df.shape)
print('\nColumns:', df.columns.tolist())
print('\n Distribution:')
print(df['species'].value_counts())
df.describe()

Shape: (150, 5)

Columns: ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

 Distribution:
species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64


,sepal_length,sepal_width,petal_length,petal_width
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000


## Q4: Separate Features (X) and Target (y)

In [11]:
X = df.drop('species', axis=1)
y = df['species']
X.head()

,sepal_length,sepal_width,petal_length,petal_width
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2


## Q5: Train–Test Split (80:20)

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print('Training size:', X_train.shape)
print('Testing size:', X_test.shape)

Training size: (120, 4)
Testing size: (30, 4)


## Q6: Build Naive Bayes Model (GaussianNB)

In [19]:
nb = GaussianNB()
nb.fit(X_train, y_train)
print('Model trained')

Model trained


## Q7: Predict Test data

In [20]:
y_pred = nb.predict(X_test)
list(y_pred)[:10]

[np.str_('versicolor'),
 np.str_('setosa'),
 np.str_('virginica'),
 np.str_('versicolor'),
 np.str_('versicolor'),
 np.str_('setosa'),
 np.str_('versicolor'),
 np.str_('virginica'),
 np.str_('versicolor'),
 np.str_('versicolor')]

## Q8: Compare Actual vs Predicted (Correct / Wrong)

In [21]:
results = pd.DataFrame({'Actual': y_test.values, 'Predicted': y_pred})
results['Status'] = results.apply(lambda r: 'Correct' if r.Actual == r.Predicted else 'Wrong', axis=1)
results.head(20)

,Actual,Predicted,Status
0,versicolor,versicolor,Correct
1,setosa,setosa,Correct
2,virginica,virginica,Correct
3,versicolor,versicolor,Correct
4,versicolor,versicolor,Correct
5,setosa,setosa,Correct
6,versicolor,versicolor,Correct
7,virginica,virginica,Correct
8,versicolor,versicolor,Correct
9,versicolor,versicolor,Correct


## Q9: Compute Accuracy & Evaluation Metrics

In [22]:
print('Accuracy:', accuracy_score(y_test, y_pred))
print('\nConfusion Matrix:\n', confusion_matrix(y_test, y_pred))
print('\nClassification Report:\n', classification_report(y_test, y_pred))

Accuracy: 1.0

Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



## Q10: Conclusion

> In this assignment, we explored the Naive Bayes algorithm as a simple yet powerful probabilistic classification technique. By applying it to the dataset, we observed how the assumption of feature independence allows the model to perform efficiently even with limited data and computational resources. The results demonstrated that Naive Bayes can achieve reliable accuracy, especially in scenarios such as text classification and categorical data problems.

>Despite its simplicity, the model has limitations—primarily the strong independence assumption, which may not hold true in real-world datasets. However, its speed, scalability, and effectiveness make it a valuable baseline model in machine learning workflows. Overall, this study highlights the importance of understanding both the strengths and constraints of Naive Bayes when applying it to practical problems.