# Assignment-3: k-Nearest Neighbour (kNN) on Iris Dataset

**Objective:** Implement and understand the k-NN classification algorithm using Python ML libraries.

Dataset: **Iris (UCI Repository)**
---

## 🔹 Step 1: Import Libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns
print('Libraries imported.')

Libraries imported.


## 🔹 Step 2: Load Iris Dataset

In [2]:
df = sns.load_dataset('iris')
df.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


## 🔹 Step 3: Split Features and Target

In [4]:
X = df.iloc[:, 0:4]
y = df['species']
print(X.shape, y.shape)

(150, 4) (150,)


## 🔹 Step 4: Train–Test Split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42)

print('Train size:', X_train.shape)
print('Test size:', X_test.shape)

Train size: (105, 4)
Test size: (45, 4)


## 🔹 Step 5: Build kNN Model (k = 3)

In [6]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
print('Model trained.')

Model trained.


## 🔹 Step 6: Make Predictions

In [7]:
y_pred = knn.predict(X_test)
list(y_pred)[:10]

['versicolor',
 'setosa',
 'virginica',
 'versicolor',
 'versicolor',
 'setosa',
 'versicolor',
 'virginica',
 'versicolor',
 'versicolor']

## 🔹 Step 7: Show Correct and Wrong Predictions

In [8]:
results = pd.DataFrame({
    'Actual': y_test.values,
    'Predicted': y_pred
})

results['Status'] = results.apply(lambda r: 'Correct' if r.Actual == r.Predicted else 'Wrong', axis=1)
results.head(20)

,Actual,Predicted,Status
0,versicolor,versicolor,Correct
1,setosa,setosa,Correct
2,virginica,virginica,Correct
3,versicolor,versicolor,Correct
4,versicolor,versicolor,Correct
5,setosa,setosa,Correct
6,versicolor,versicolor,Correct
7,virginica,virginica,Correct
8,versicolor,versicolor,Correct
9,versicolor,versicolor,Correct


## 🔹 Step 8: Accuracy & Evaluation

In [9]:
print('Accuracy:', accuracy_score(y_test, y_pred))
print('\nClassification Report:')
print(classification_report(y_test, y_pred))
print('\nConfusion Matrix:')
print(confusion_matrix(y_test, y_pred))

Accuracy: 1.0

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        19
  versicolor       1.00      1.00      1.00        13
   virginica       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45


Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
